/**
 * Auto generation mode enumeration
 */
export enum AutoGenerateMode {
    NONE = 'none',     // Disable auto generation
    DAILY = 'daily',   // Daily auto generation
    WORKDAY = 'workday' // Only workday auto generation
}

/**
 * Storage mode enumeration
 */
export enum StorageMode {
    TRADITIONAL = 'traditional', // Traditional mode (archive by year/month folders)
    SINGLE_FILE = 'single_file', // Single file mode (overwrite the same file daily)
    BOTH = 'both'                // Use both modes
}

/**
 * Settings UI Language
 */
export enum Language {
    AUTO = 'auto',
    ZH = 'zh',
    EN = 'en',
    AR = 'ar'
}

/**
 * Plugin settings interface
 */
export interface TaskoratorSettings {
    // Basic configuration
    storageMode: StorageMode;      // Storage mode
    singleFilePath: string;        // File path for single file mode
    rootDir: string;               // Root directory for task files (traditional mode)
    autoGenerateMode: AutoGenerateMode; // Auto-generation mode
    language: string;            // UI language
    outputLanguage: string;      // Output (generation) language

    // Template configuration
    templateZh: string;            // Chinese task template
    templateEn: string;            // English task template
    templateAr: string;            // Arabic task template

    // New: User-defined custom template
    customTemplate: string;

    // New: Flag for using custom template
    hasCustomTemplate: boolean;
}

/**
 * Default Chinese template
 */
export const DEFAULT_TEMPLATE_ZH = `## {{dateWithIcon}}（{{weekday}}）
// 这是一个默认模板。你可以根据自己的需求自定义。
// 以 // 开头的行在生成的笔记中将被跳过。

> 🕒 生成时间：{{time}}

// 每天都会出现的自动化任务
### ✨ 每日习惯 #every-day

- [ ] 🪥 刷牙
- [ ] 💧 喝 2L 水
- [ ] 📝 复盘今日目标

---

// 仅在工作日（周一至周五）显示的任务
### 💼 工作任务 #every-workday

- [ ] 检查并回复邮件
- [ ] 团队同步会议 #every(mon, wed, fri)
- [ ] 每周报告更新 #every fri

---

// 按周、天或日期进行高级调度的示例
### 🎨 个人兴趣与爱好

- [ ] 📚 阅读 30 分钟 #every(mon, tue, wed, thu, fri)
- [ ] 🏋️ 健身房锻炼 #every(mon, wed, fri)
- [ ] 🧺 整理桌面 #every sun
- [ ] 🍛 尝试新餐厅 #every(month(1, 15))

---

*Generated by Taskorator*`;

/**
 * Default English template
 */
export const DEFAULT_TEMPLATE_EN = `## {{dateWithIcon}} ({{weekday}})
// This is a default template. You can customize it to fit your needs.
// Lines starting with // will be ignored in the generated note.

> 🕒 Generated At: {{time}}

// Automated tasks appearing every single day
### ✨ Daily Routine #every-day

- [ ] 🪥 Brush teeth
- [ ] 💧 Drink 2L of water
- [ ] 📝 Review today's goals

---

// Tasks shown only on workdays (Mon-Fri)
### 💼 Work Tasks #every-workday

- [ ] Check and reply to emails
- [ ] Team sync meeting #every(mon, wed, fri)
- [ ] Weekly report update #every fri

---

// Examples of advanced scheduling by week, day, or date
### 🎨 Personal & Hobbies

- [ ] 📚 Read for 30 minutes #every(mon, tue, wed, thu, fri)
- [ ] 🏋️ Gym workout #every(mon, wed, fri)
- [ ] 🧺 Organize desk #every sun
- [ ] 🍛 Try a new restaurant #every(month(1, 15))

---

*Generated by Taskorator*`;

/**
 * Default Arabic template
 */
export const DEFAULT_TEMPLATE_AR = `## {{dateWithIcon}} ({{weekday}})
// هذا قالب افتراضي. يمكنك تخصيصه ليناسب احتياجاتك.
// الأسطر التي تبدأ بـ // سيتم تجاهلها في الملاحظة المولدة.

> 🕒 وقت التوليد: {{time}}

// مهام مؤتمتة تظهر كل يوم
### ✨ الروتين اليومي #every-day

- [ ] 🪥 تنظيف الأسنان
- [ ] 💧 شرب 2 لتر من الماء
- [ ] 📝 مراجعة أهداف اليوم

---

// المهام التي تظهر فقط في أيام العمل (الاثنين - الجمعة)
### 💼 مهام العمل #every-workday

- [ ] مراجعة والرد على رسائل البريد
- [ ] اجتماع المزامنة #every(mon, wed, fri)
- [ ] تحديث التقرير الأسبوعي #every fri

---

// أمثلة على الجدولة المتقدمة حسب الأسبوع أو اليوم أو التاريخ
### 🎨 الهوايات والاهتمامات

- [ ] 📚 القراءة لمدة 30 دقيقة #every(mon, tue, wed, thu, fri)
- [ ] 🏋️ تمرين رياضي #every(mon, wed, fri)
- [ ] 🧺 ترتيب المكتب #every sun
- [ ] 🍛 تجربة مطعم جديد #every(month(1, 15))

---

*توليد بواسطة Taskorator*`;

/**
 * Default settings
 */
export const DEFAULT_SETTINGS: TaskoratorSettings = {
    storageMode: StorageMode.TRADITIONAL,
    singleFilePath: 'Tasks.md',
    rootDir: 'Tasks',
    autoGenerateMode: AutoGenerateMode.DAILY,
    language: Language.AUTO,
    outputLanguage: Language.AUTO,
    templateZh: DEFAULT_TEMPLATE_ZH,
    templateEn: DEFAULT_TEMPLATE_EN,
    templateAr: DEFAULT_TEMPLATE_AR,
    customTemplate: '', // Default is empty, meaning use the language-specific default template
    hasCustomTemplate: false // Default is not use custom template
};
