/**
 * Auto generation mode enumeration
 */
export enum AutoGenerateMode {
    NONE = 'none',     // Disable auto generation
    DAILY = 'daily',   // Daily auto generation
    WORKDAY = 'workday' // Only workday auto generation
}

/**
 * Storage mode enumeration
 */
export enum StorageMode {
    TRADITIONAL = 'traditional', // Traditional mode (archive by year/month folders)
    SINGLE_FILE = 'single_file', // Single file mode (overwrite the same file daily)
    BOTH = 'both'                // Use both modes
}

/**
 * Settings UI Language
 */
export enum Language {
    AUTO = 'auto',
    ZH = 'zh',
    EN = 'en',
    AR = 'ar'
}

/**
 * Plugin settings interface
 */
export interface TaskoratorSettings {
    // Basic configuration
    storageMode: StorageMode;      // Storage mode
    singleFilePath: string;        // File path for single file mode
    rootDir: string;               // Root directory for task files (traditional mode)
    autoGenerateMode: AutoGenerateMode; // Auto-generation mode
    language: string;            // UI language

    // Template configuration
    templateZh: string;            // Chinese task template
    templateEn: string;            // English task template
    templateAr: string;            // Arabic task template

    // New: User-defined custom template
    customTemplate: string;

    // New: Flag for using custom template
    hasCustomTemplate: boolean;
}

/**
 * Default Chinese template
 */
export const DEFAULT_TEMPLATE_ZH = `## {{dateWithIcon}}（{{weekday}}）
// 这是一个默认模板。你可以根据自己的需求自定义。
// lines starting with // will be skipped

> 🕒 生成时间：{{time}}

### 🧘 每日必做
---

- [ ] 🧘 冥想 10 分钟 #every-day
- [ ] 💧 喝 8 杯水 #every-day
- [ ] 📝 复盘今日进度 #every-day

### 💼 工作任务 #every-workday
---

- [ ] 整理今日待办清单 #every-day
- [ ] 检查并回复邮件 #every-day
- [ ] 团队站会 #every mon, wed, fri
- [ ] 周报更新 #every fri

### 🎨 个人兴趣
---

- [ ] 📚 阅读 30 分钟 #every mon, tue, wed, thu, fri
- [ ] 🏋️ 健身房锻炼 #every(mon, wed, fri)
- [ ] 🏸 羽毛球 #every sat
- [ ] 🧺 整理桌面 #every sun
- [ ] 🍛 尝试新餐厅 #every(month(1, 15))

---
*Generated by Taskorator*`;

/**
 * Default English template
 */
export const DEFAULT_TEMPLATE_EN = `## {{dateWithIcon}} ({{weekday}})
// This is a default template. You can customize it to fit your needs.
// Lines starting with // will be ignored in the generated note.

> 🕒 Generated At: {{time}}

### 🧘 Daily Routine
---

- [ ] 🧘 Meditation 10 min #every-day
- [ ] 💧 Drink 2L of water #every-day
- [ ] 📝 Review today's goals #every-day

### 💼 Work Tasks #every-workday
---

- [ ] Organize today's task list #every-day
- [ ] Check and reply to emails #every-day
- [ ] Team sync meeting #every(mon, wed, fri)
- [ ] Weekly report update #every fri

### 🎨 Personal & Hobbies
---

- [ ] 📚 Read for 30 minutes #every(mon, tue, wed, thu, fri)
- [ ] 🏋️ Gym workout #every(mon, wed, fri)
- [ ] 🏸 Badminton #every sat
- [ ] 🧺 Organize desk #every sun
- [ ] 🍛 Try a new restaurant #every(month(1, 15))

---
*Generated by Taskorator*`;

/**
 * Default Arabic template
 */
export const DEFAULT_TEMPLATE_AR = `## {{dateWithIcon}} ({{weekday}})
// هذا قالب افتراضي. يمكنك تخصيصه ليناسب احتياجاتك.
// الأسطر التي تبدأ بـ // سيتم تجاهلها في الملاحظة المولدة.

> 🕒 وقت التوليد: {{time}}

### 🧘 الروتين اليومي
---

- [ ] 🧘 تأمل لمدة 10 دقائق #every-day
- [ ] 💧 شرب 2 لتر من الماء #every-day
- [ ] 📝 مراجعة أهداف اليوم #every-day

### 💼 مهام العمل #every-workday
---

- [ ] تنظيم قائمة مهام اليوم #every-day
- [ ] مراجعة والرد على رسائل البريد #every-day
- [ ] اجتماع المزامنة #every(mon, wed, fri)
- [ ] تحديث التقرير الأسبوعي #every fri

### 🎨 الهوايات والاهتمامات
---

- [ ] 📚 القراءة لمدة 30 دقيقة #every(mon, tue, wed, thu, fri)
- [ ] 🏋️ تمرين رياضي #every(mon, wed, fri)
- [ ] 🏸 رياضة الريشة #every sat
- [ ] 🧺 ترتيب المكتب #every sun
- [ ] 🍛 تجربة مطعم جديد #every(month(1, 15))

---
*توليد بواسطة Taskorator*`;

/**
 * Default settings
 */
export const DEFAULT_SETTINGS: TaskoratorSettings = {
    storageMode: StorageMode.TRADITIONAL,
    singleFilePath: 'Tasks.md',
    rootDir: 'Tasks',
    autoGenerateMode: AutoGenerateMode.DAILY,
    language: Language.AUTO,
    templateZh: DEFAULT_TEMPLATE_ZH,
    templateEn: DEFAULT_TEMPLATE_EN,
    templateAr: DEFAULT_TEMPLATE_AR,
    customTemplate: '', // Default is empty, meaning use the language-specific default template
    hasCustomTemplate: false // Default is not use custom template
};
